### ISSUE TITLE
is it possible to add support for yeelink.light.ceiling5 ?

### ISSUE THREAD

**Issue by wkamlun** [viestursr/homebridge-xiaomi-yeelight#3]
is it possible to add support for yeelink.light.ceiling5 ?

Thanks a lot

**Comment by viestursr** [comment]
@wkamlun I think so, unless that's some old light with an outdated FW and API. But I expect no issues. Will add it today and let you know when you can test it. Cheers!

**Comment by viestursr** [comment]
@wkamlun I've just pushed 1.1.5 that should support your model. Please try it out :)

**Comment by wkamlun** [comment]
It's work, thanks a lot
    Viesturs Ruzans ***@***.***>) 在 2022年2月23日星期三 上午01:44:28 [GMT+8] 寫道：  
 
 


@wkamlun I've just pushed 1.1.5 that should support your model. Please try it out :)
